# 1. Insert an element at a specific position in a list

In [1]:
# Insert an element at a specific position
my_list = [10, 20, 30, 40]
pos = 2  # insert at index 2
element = 25
my_list.insert(pos, element)
print("Updated List:", my_list)

Updated List: [10, 20, 25, 30, 40]


# 2. Find max and min without max()/min()

In [2]:
numbers = [5, 8, 2, 9, 1, 6]
max_val = numbers[0]
min_val = numbers[0]
for num in numbers:
    if num > max_val:
        max_val = num
    if num < min_val:
        min_val = num
print("Maximum:", max_val)
print("Minimum:", min_val)

Maximum: 9
Minimum: 1


# 3. Remove all negative numbers from a list

In [3]:
nums = [10, -3, 5, -7, 2, -1, 8]
positive_nums = [n for n in nums if n >= 0]
print("Without negatives:", positive_nums)

Without negatives: [10, 5, 2, 8]


# 4. Reverse a list using slicing and a loop

In [4]:
lst = [1, 2, 3, 4, 5]
print("Reversed (slicing):", lst[::-1])
reversed_list = []
for i in range(len(lst)-1, -1, -1):
    reversed_list.append(lst[i])
print("Reversed (loop):", reversed_list)

Reversed (slicing): [5, 4, 3, 2, 1]
Reversed (loop): [5, 4, 3, 2, 1]


# 5. Merge two sorted lists into a single sorted list

In [5]:
list1 = [1, 3, 5, 7]
list2 = [2, 4, 6, 8]
merged = sorted(list1 + list2)
print("Merged Sorted List:", merged)

Merged Sorted List: [1, 2, 3, 4, 5, 6, 7, 8]


# 6. Convert a list into a tuple and vice versa

In [6]:
my_list = [1, 2, 3, 4]
my_tuple = tuple(my_list)
print("As Tuple:", my_tuple)
converted_back = list(my_tuple)
print("Back to List:", converted_back)

As Tuple: (1, 2, 3, 4)
Back to List: [1, 2, 3, 4]


# 7. Find the common elements in two sets

In [7]:
set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7}
common = set1 & set2
print("Common elements:", common)

Common elements: {4, 5}


# 8. Remove duplicate elements from a list using a set

In [8]:
numbers = [1, 2, 2, 3, 4, 4, 5]
unique = list(dict.fromkeys(numbers))  # preserves order
print("Without duplicates:", unique)

Without duplicates: [1, 2, 3, 4, 5]


# 9. Check if two sets are disjoint

In [9]:
a = {1, 2, 3}
b = {4, 5, 6}
print("Are disjoint?", a.isdisjoint(b))

Are disjoint? True


# 10. Create a set from user input and check membership of an element

In [10]:
# Example: input: 1 2 3 4 5
user_input = input("Enter elements separated by space: ").split()
try:
    user_set = set(map(int, user_input))
except ValueError:
    user_set = set(user_input)
element = input("Enter an element to check: ")
try:
    element_converted = int(element)
except ValueError:
    element_converted = element
print("Element present?", element_converted in user_set)

Enter elements separated by space:  1 2 3 5
Enter an element to check:  3


Element present? True


# 11. Count frequency of each character in a string using a dictionary

In [11]:
text = "programming"
freq = {}
for char in text:
    freq[char] = freq.get(char, 0) + 1
print("Character Frequency:", freq)

Character Frequency: {'p': 1, 'r': 2, 'o': 1, 'g': 2, 'a': 1, 'm': 2, 'i': 1, 'n': 1}


# 12. Create a dictionary from two lists: keys and values

In [12]:
keys = ['name', 'age', 'city']
values = ['Alice', 25, 'New York']
my_dict = dict(zip(keys, values))
print("Created Dictionary:", my_dict)

Created Dictionary: {'name': 'Alice', 'age': 25, 'city': 'New York'}


# 13. Sort a dictionary by its values

In [13]:
data = {'a': 3, 'b': 1, 'c': 5, 'd': 2}
sorted_dict = dict(sorted(data.items(), key=lambda item: item[1]))
print("Sorted by Values:", sorted_dict)

Sorted by Values: {'b': 1, 'd': 2, 'a': 3, 'c': 5}


# 14. Merge two dictionaries into one

In [14]:
dict1 = {'x': 1, 'y': 2}
dict2 = {'y': 3, 'z': 4}
merged = dict1.copy()
merged.update(dict2)
print("Merged Dictionary:", merged)

Merged Dictionary: {'x': 1, 'y': 3, 'z': 4}


# 15. Find the key with the highest value in a dictionary

In [15]:
scores = {'Alice': 85, 'Bob': 92, 'Charlie': 78}
max_key = max(scores, key=scores.get)
print("Highest Value Key:", max_key, "→", scores[max_key])

Highest Value Key: Bob → 92


# 16. Function that checks if a number is prime

In [16]:
def is_prime(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0:
        return False
    i = 3
    while i * i <= n:
        if n % i == 0:
            return False
        i += 2
    return True
print(is_prime(7))

True


# 17. Function that returns number of vowels in a string

In [17]:
def count_vowels(s):
    vowels = 'aeiouAEIOU'
    return sum(1 for char in s if char in vowels)
print(count_vowels('Hello World'))

3


# 18. Function that returns only even numbers from a list

In [18]:
def get_even(nums):
    return [n for n in nums if n % 2 == 0]
print(get_even([1,2,3,4,5,6]))

[2, 4, 6]


# 19. Recursive function to calculate factorial

In [19]:
def factorial(n):
    if n == 0 or n == 1:
        return 1
    return n * factorial(n-1)
print(factorial(5))

120


# 20. Function that returns the nth Fibonacci number using recursion

In [20]:
def fibonacci(n):
    if n <= 1:
        return n
    return fibonacci(n-1) + fibonacci(n-2)
print(fibonacci(7))

13


# 21. Function that returns a dictionary with the count of each element in a list

In [21]:
def count_elements(lst):
    counts = {}
    for i in lst:
        counts[i] = counts.get(i, 0) + 1
    return counts
print(count_elements([1,2,2,3,3,3]))

{1: 1, 2: 2, 3: 3}


# 22. Function that returns the longest word from a list of words

In [22]:
def longest_word(words):
    if not words:
        return None
    return max(words, key=len)
print(longest_word(['apple','banana','kiwi']))

banana


# 23. Function that accepts any number of arguments and returns their average

In [23]:
def average(*args):
    if not args:
        return 0
    return sum(args)/len(args)
print(average(10,20,30))

20.0


# 24. Function with default arguments for username and age and print greeting

In [24]:
def greet(name='User', age=18):
    print(f'Hello {name}, you are {age} years old.')
greet()
greet('Alice', 22)

Hello User, you are 18 years old.
Hello Alice, you are 22 years old.


# 25. Use a lambda to sort a list of tuples by the second element

In [25]:
pairs = [(1,5),(3,1),(2,4)]
pairs.sort(key=lambda x: x[1])
print(pairs)

[(3, 1), (2, 4), (1, 5)]


# 26. Function that accepts a list and a condition function and returns filtered list

In [26]:
def filter_list(nums, condition):
    return [n for n in nums if condition(n)]
print(filter_list([1,2,3,4,5,6], lambda x: x%2==0))

[2, 4, 6]


# 27. Function to check whether a string is a palindrome

In [27]:
def is_palindrome(s):
    s_clean = ''.join(ch.lower() for ch in s if ch.isalnum())
    return s_clean == s_clean[::-1]
print(is_palindrome('Madam'))

True


# 28. Function to return the GCD of two numbers

In [28]:
def gcd(a,b):
    while b:
        a, b = b, a % b
    return a
print(gcd(54,24))

6


# 29. Function that returns another function (closure) that adds a fixed number

In [29]:
def add_fixed(num):
    def adder(x):
        return x + num
    return adder
add5 = add_fixed(5)
print(add5(10))

15


# 30. Function to flatten a nested list

In [30]:
def flatten(nested):
    flat = []
    for sub in nested:
        for item in sub:
            flat.append(item)
    return flat
print(flatten([[1,2],[3,4]]))

[1, 2, 3, 4]


# 31. Recursive function to calculate the sum of a list

In [31]:
def recursive_sum(lst):
    if not lst:
        return 0
    return lst[0] + recursive_sum(lst[1:])
print(recursive_sum([1,2,3,4]))

10


# 32. Function that takes two lists and returns a dictionary mapping first to second

In [32]:
def list_to_dict(keys, values):
    return dict(zip(keys, values))
print(list_to_dict(['a','b','c'], [1,2,3]))

{'a': 1, 'b': 2, 'c': 3}


# 33. Create a function to return all prime numbers in a range

In [33]:
def primes_in_range(start, end):
    return [n for n in range(start, end+1) if is_prime(n)]
print(primes_in_range(10,30))

[11, 13, 17, 19, 23, 29]


# 34. Function that mimics zip()

In [34]:
def my_zip(list1, list2):
    return [(list1[i], list2[i]) for i in range(min(len(list1), len(list2)))]
print(my_zip([1,2,3], ['a','b','c']))

[(1, 'a'), (2, 'b'), (3, 'c')]


# 35. Function that calculates compound interest given principal, rate, time

In [35]:
def compound_interest(p, r, t):
    amount = p * (1 + r/100) ** t
    return round(amount - p, 2)
print(compound_interest(1000, 5, 2))

102.5


# 36. Use a lambda to add 10 to a number

In [36]:
add10 = lambda x: x + 10
print(add10(5))

15


# 37. Sort a list of tuples based on second element using lambda

In [37]:
tuples = [(1,3),(2,1),(3,2)]
sorted_tuples = sorted(tuples, key=lambda x: x[1])
print(sorted_tuples)

[(2, 1), (3, 2), (1, 3)]


# 38. Sort a list of dictionaries by the value of a specific key using lambda

In [38]:
people = [{'name':'A','age':30},{'name':'B','age':25},{'name':'C','age':35}]
sorted_people = sorted(people, key=lambda x: x['age'])
print(sorted_people)

[{'name': 'B', 'age': 25}, {'name': 'A', 'age': 30}, {'name': 'C', 'age': 35}]


# 39. Use lambda with map() to square each element in a list

In [39]:
nums = [1,2,3,4]
squares = list(map(lambda x: x**2, nums))
print(squares)

[1, 4, 9, 16]


# 40. Use lambda with filter() to get only even numbers from a list

In [40]:
nums = [1,2,3,4,5,6]
evens = list(filter(lambda x: x%2==0, nums))
print(evens)

[2, 4, 6]


# 41. Use lambda with reduce() to multiply all elements in a list

In [41]:
from functools import reduce
nums = [1,2,3,4]
product = reduce(lambda x,y: x*y, nums)
print(product)

24


# 42. Create a lambda to check if a number is divisible by both 3 and 5

In [42]:
div35 = lambda x: x%3==0 and x%5==0
print(div35(15), div35(10))

True False


# 43. Use lambda with map() to convert Celsius to Fahrenheit

In [43]:
celsius = [0,10,20,30]
fahrenheit = list(map(lambda c: (c*9/5)+32, celsius))
print(fahrenheit)

[32.0, 50.0, 68.0, 86.0]


# 44. Use lambda to sort a list of strings based on their length

In [44]:
fruits = ['apple','kiwi','banana','fig']
sorted_by_length = sorted(fruits, key=lambda s: len(s))
print(sorted_by_length)

['fig', 'kiwi', 'apple', 'banana']


# 45. Lambda that returns True if a string starts with a vowel

In [45]:
starts_vowel = lambda s: s[0].lower() in 'aeiou' if s else False
print(starts_vowel('apple'), starts_vowel('banana'))

True False


# 46. Use lambda inside a function that returns a power function (closure)

In [46]:
def power_function(n):
    return lambda x: x ** n
square = power_function(2)
print(square(5))

25


# 47. Lambda to extract domain names from a list of email addresses

In [47]:
emails = ['alice@example.com','bob@test.org']
domains = list(map(lambda e: e.split('@')[-1], emails))
print(domains)

['example.com', 'test.org']


# 48. Use lambda with filter() to remove empty strings from a list

In [48]:
strings = ['a','','b','', 'c']
non_empty = list(filter(lambda s: s != '', strings))
print(non_empty)

['a', 'b', 'c']


# 49. Create a list of lambda functions each returning multiples of 5

In [49]:
funcs = [ (lambda n: (lambda x: x*n))(i) for i in range(1,6) ]  # closures to capture i
for f in funcs:
    print(f(5))  # prints 5,10,15,20,25

5
10
15
20
25


# 50. Use a lambda to find max element in list of tuples by sum of tuple elements

In [50]:
tuples = [(1,2),(3,4),(0,10)]
max_by_sum = max(tuples, key=lambda t: sum(t))
print(max_by_sum)

(0, 10)


# 51. Use lambda and map() to convert a list of integers to strings

In [51]:
nums = [1,2,3]
str_nums = list(map(lambda x: str(x), nums))
print(str_nums)

['1', '2', '3']


# 52. Use lambda with filter() to extract palindromic words from a list

In [52]:
words = ['level','hello','radar','world']
palindromes = list(filter(lambda w: w==w[::-1], words))
print(palindromes)

['level', 'radar']


# 53. Use lambda with sorted() to sort list of strings by their last character

In [53]:
words = ['apple','banana','pear','kiwi']
sorted_last = sorted(words, key=lambda s: s[-1])
print(sorted_last)

['banana', 'apple', 'kiwi', 'pear']


# 54. Combine lambda, map(), and zip() to add two lists element-wise

In [54]:
a = [1,2,3]
b = [4,5,6]
summed = list(map(lambda x: x[0]+x[1], zip(a,b)))
print(summed)

[5, 7, 9]


# 55. Use lambda to count how many strings in a list have length > 5

In [55]:
strings = ['hello','international','python','data']
count = sum(map(lambda s: 1 if len(s)>5 else 0, strings))
print(count)

2


# 56. Create a text file and write 'Hello, World!' into it

In [56]:
with open('hello_world.txt','w') as f:
    f.write('Hello, World!')
print('hello_world.txt created')

hello_world.txt created


# 57. Read contents of a file and print line by line

In [57]:
with open('hello_world.txt','r') as f:
    for line in f:
        print(line.strip())

Hello, World!


# 58. Append a new line to an existing file without overwriting

In [58]:
with open('hello_world.txt','a') as f:
    f.write('\nAppended line.')
print('Appended.')

Appended.


# 59. Count the number of words in a given file

In [59]:
with open('hello_world.txt','r') as f:
    text = f.read()
print('Word count:', len(text.split()))

Word count: 4


# 60. Copy contents of one file to another

In [60]:
with open('hello_world.txt','r') as src, open('copy_hello.txt','w') as dst:
    dst.write(src.read())
print('Copied to copy_hello.txt')

Copied to copy_hello.txt


# 61. Read a file and count how many lines it has

In [61]:
with open('hello_world.txt','r') as f:
    lines = f.readlines()
print('Number of lines:', len(lines))

Number of lines: 2


# 62. Read a file and display only lines that contain 'Python'

In [62]:
with open('hello_world.txt','r') as f:
    for line in f:
        if 'Python' in line:
            print(line.strip())

# 63. Function that takes filename and returns number of characters in file

In [63]:
def count_chars(filename):
    with open(filename,'r') as f:
        return len(f.read())
print(count_chars('hello_world.txt'))

28


# 64. Divide two numbers and handle ZeroDivisionError

In [64]:
try:
    a = float(input('Enter numerator: '))
    b = float(input('Enter denominator: '))
    print('Result:', a/b)
except ZeroDivisionError:
    print('Cannot divide by zero.')

Enter numerator:  10
Enter denominator:  2


Result: 5.0


# 65. Read a number and raise ValueError if negative

In [65]:
num = float(input('Enter a number: '))
if num < 0:
    raise ValueError('Negative number entered')
print('Number is:', num)

Enter a number:  5


Number is: 5.0


# 66. Open a file that may not exist and handle FileNotFoundError

In [66]:
try:
    with open('maybe_missing.txt','r') as f:
        print(f.read())
except FileNotFoundError:
    print('File not found.')

File not found.


# 67. Create function that handles both ValueError and TypeError while taking input

In [67]:
def get_int(prompt):
    try:
        return int(input(prompt))
    except (ValueError, TypeError):
        print('Invalid input.')
        return None
print(get_int('Enter int: '))

Enter int:  5


5


# 68. Use try...except...finally to handle exceptions and close a file properly

In [68]:
try:
    f = open('hello_world.txt','r')
    print(f.read())
except Exception as e:
    print('Error:', e)
finally:
    f.close()
    print('File closed in finally.')

Hello, World!
Appended line.
File closed in finally.


# 69. Attempt to convert user input to integer and handle invalid input

In [101]:
try:
    x = int(input('Enter integer: '))
    print('You entered', x)
except ValueError:
    print('That is not a valid integer.')

Enter integer:  5


You entered 5


# 70. Use try...except to read from a file and display custom error message

In [70]:
try:
    with open('missing_file.txt','r') as f:
        print(f.read())
except Exception:
    print('Could not read the file. Check path/permissions.')

Could not read the file. Check path/permissions.


# 71. Create a 4x4 NumPy array filled with random integers 10 to 50 and replace odds with -1

In [71]:
import numpy as np
arr = np.random.randint(10,51,(4,4))
arr[arr % 2 != 0] = -1
print(arr)

[[-1 -1 -1 38]
 [14 16 42 -1]
 [-1 -1 24 -1]
 [12 -1 38 36]]


# 72. Given 1D NumPy array, compute difference between each element and mean

In [72]:
import numpy as np
arr = np.array([10,20,30,40,50])
mean = arr.mean()
diff = arr - mean
print('Differences:', diff)

Differences: [-20. -10.   0.  10.  20.]


# 73. Create a 5x5 identity matrix and change diagonal values to 9

In [73]:
import numpy as np
mat = np.identity(5)
mat[np.diag_indices(5)] = 9
print(mat)

[[9. 0. 0. 0. 0.]
 [0. 9. 0. 0. 0.]
 [0. 0. 9. 0. 0.]
 [0. 0. 0. 9. 0.]
 [0. 0. 0. 0. 9.]]


# 74. Stack two NumPy arrays of shape (3,4) vertically and horizontally

In [74]:
import numpy as np
a = np.random.randint(1,10,(3,4))
b = np.random.randint(1,10,(3,4))
print('Vertical stack:\n', np.vstack((a,b)))
print('Horizontal stack:\n', np.hstack((a,b)))

Vertical stack:
 [[1 7 2 1]
 [6 8 2 4]
 [1 3 7 3]
 [4 9 9 4]
 [6 6 8 2]
 [1 6 5 5]]
Horizontal stack:
 [[1 7 2 1 4 9 9 4]
 [6 8 2 4 6 6 8 2]
 [1 3 7 3 1 6 5 5]]


# 75. Extract all rows from 2D array where first element > 50

In [75]:
import numpy as np
arr = np.random.randint(0,100,(6,4))
filtered = arr[arr[:,0] > 50]
print(filtered)

[[86  5 61 13]
 [65 50 26 87]]


# 76. Create a 6x6 array and extract 3x3 center block

In [76]:
import numpy as np
arr = np.arange(36).reshape(6,6)
center = arr[1:4,1:4]
print(center)

[[ 7  8  9]
 [13 14 15]
 [19 20 21]]


# 77. Normalize a 1D array (0-1 scale)

In [77]:
import numpy as np
arr = np.array([10,20,30,40])
norm = (arr - arr.min()) / (arr.max() - arr.min())
print('Normalized:', norm)

Normalized: [0.         0.33333333 0.66666667 1.        ]


# 78. Given 2D array, replace elements greater than average with the average

In [78]:
import numpy as np
arr = np.random.randint(1,100,(4,4)).astype(float)
avg = arr.mean()
arr[arr > avg] = avg
print(arr)

[[30.  55.5 55.5 34. ]
 [29.  42.  55.5 55.5]
 [55.5 22.  46.  55.5]
 [55.5 20.  38.  55.5]]


# 79. Find indices of top 3 maximum elements in 1D array

In [79]:
import numpy as np
arr = np.array([10,50,30,80,60])
indices = arr.argsort()[-3:][::-1]
print('Top 3 indices:', indices)

Top 3 indices: [3 4 1]


# 80. Given 3D array shape (2,3,4), calculate sum across axis 1 and axis 2

In [80]:
import numpy as np
arr = np.random.randint(1,10,(2,3,4))
print('Sum across axis 1:', arr.sum(axis=1))
print('Sum across axis 2:', arr.sum(axis=2))

Sum across axis 1: [[13 16 10 15]
 [17 18 16 14]]
Sum across axis 2: [[14 16 24]
 [25 21 19]]


# 81. Load CSV into DataFrame and display top 5 rows

In [81]:
import pandas as pd
# df = pd.read_csv('data.csv')  # uncomment and set filename
# print(df.head())
print('Replace with your CSV file path to load data into df')

Replace with your CSV file path to load data into df


# 82. Check for missing values and count them column-wise

In [82]:
# print(df.isnull().sum())  # run after loading df
print('Use df.isnull().sum() after loading your DataFrame')

Use df.isnull().sum() after loading your DataFrame


# 83. Drop all rows from DataFrame that contain any missing values

In [83]:
# df_clean = df.dropna()
# print(df_clean)
print('Use df.dropna() to remove rows with missing values')

Use df.dropna() to remove rows with missing values


# 84. Fill missing values in a specific column with column's mean

In [84]:
# df['col'] = df['col'].fillna(df['col'].mean())
print('Use df["col"].fillna(df["col"].mean(), inplace=True)')

Use df["col"].fillna(df["col"].mean(), inplace=True)


# 85. Rename multiple columns in a DataFrame using a dictionary

In [85]:
# df.rename(columns={'old1':'new1','old2':'new2'}, inplace=True)
print('Use df.rename(...) to rename columns')

Use df.rename(...) to rename columns


# 86. Select rows where a column's value is between two values

In [86]:
# subset = df[(df['Age'] >= 10) & (df['Age'] <= 20)]
print('Use boolean indexing to filter rows between values')

Use boolean indexing to filter rows between values


# 87. Replace all values greater than a threshold with a fixed value

In [87]:
# df[df > 100] = 100
print('Use df[df > threshold] = fixed_value')

Use df[df > threshold] = fixed_value


# 88. Filter rows where two or more conditions are true

In [88]:
# filtered = df[(df['Gender']=='Male') & (df['Age']>30)]
print('Use & and | for multiple conditions (with parentheses)')

Use & and | for multiple conditions (with parentheses)


# 89. Create a new column that is the result of an arithmetic operation

In [89]:
# df['Total'] = df['Price'] * df['Quantity']
print('Create new columns by assignment')

Create new columns by assignment


# 90. Group the data by one column and calculate the average of another column

In [90]:
# avg_salary = df.groupby('Department')['Salary'].mean()
print('Use groupby and aggregation functions')

Use groupby and aggregation functions


# 91. Group by two columns and calculate multiple aggregation metrics (mean, max)

In [91]:
# grouped = df.groupby(['Department','Gender'])['Salary'].agg(['mean','max'])
print('Use agg([...]) for multiple aggregations')

Use agg([...]) for multiple aggregations


# 92. Sort a DataFrame by two columns: one ascending, one descending

In [92]:
# df.sort_values(by=['Dept','Salary'], ascending=[True, False], inplace=True)
print('Use sort_values with ascending list')

Use sort_values with ascending list


# 93. Reset the index of a DataFrame after dropping rows

In [93]:
# df.reset_index(drop=True, inplace=True)
print('Use reset_index to reindex the DataFrame')

Use reset_index to reindex the DataFrame


# 94. Create a pivot table showing the average salary by department and gender

In [94]:
# pivot = df.pivot_table(values='Salary', index='Department', columns='Gender', aggfunc='mean')
print('Use pivot_table to create summary tables')

Use pivot_table to create summary tables


# 95. Merge two DataFrames using a common key column

In [95]:
# merged = pd.merge(df1, df2, on='EmployeeID')
print('Use pd.merge for joining DataFrames')

Use pd.merge for joining DataFrames


# 96. Concatenate two DataFrames vertically and reset index

In [96]:
# combined = pd.concat([df1, df2], ignore_index=True)
print('Use pd.concat to concatenate DataFrames vertically')

Use pd.concat to concatenate DataFrames vertically


# 97. Extract the year from a column containing dates

In [97]:
# df['Year'] = pd.to_datetime(df['Date']).dt.year
print('Use pd.to_datetime and dt accessor to extract year')

Use pd.to_datetime and dt accessor to extract year


# 98. Count the number of unique values in a column

In [98]:
# print(df['Department'].nunique())
print('Use nunique() to count unique values')

Use nunique() to count unique values


# 99. Convert a categorical column into one-hot encoded format

In [99]:
# encoded = pd.get_dummies(df, columns=['Gender'])
print('Use pd.get_dummies for one-hot encoding')

Use pd.get_dummies for one-hot encoding


# 100. Apply a custom function to a column using .apply() to categorize values

In [100]:
def grade(marks):
    if marks >= 90: return 'A'
    elif marks >= 75: return 'B'
    else: return 'C'
# df['Grade'] = df['Marks'].apply(grade)
print('Define a function and use .apply() to create a new column')

Define a function and use .apply() to create a new column
